name: local-rag
channels:
  - conda-forge
  - default
dependencies:
  - python=3.12.11
  - flask=3.1.2
  - pip
  - pip:
      - langchain==1.0.8
      - langchain-classic
      - langchain-community
      - langchain-core==1.0.6
      - langchain-chroma
      - langchain-ollama
      - langchain-text-splitters